import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Poppins, Inter} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const manr = Manrope({
    subsets: ['latin'],
    weight: ['200', '300', '400', '500', '600', '700', '800',],
    variable: '--font-manr'
});
const poppins = Poppins({
    subsets: ['latin'],
    weight: ['100', '200', '400', '600', '800', '900'],
    variable: '--font-poppins'
});
const inter =
    Inter({
        subsets: ['latin'],
        variable: '--font-inter',
        weight: ['100', '200', '400', '600', '800', '900'],
    });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manr.variable} ${poppins.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
